DROP TABLE IF EXISTS Changes_Furniture;
CREATE TABLE Changes_Furniture(
	ID SERIAL PRIMARY KEY,
	UPDATED_AT TIMESTAMP,
	OLD_FURNITURE_NAME VARCHAR(50) NOT NULL,
	NEW_FURNITURE_NAME VARCHAR(50) NOT NULL
);

CREATE OR REPLACE FUNCTION Update_Furniture_Details() RETURNS trigger AS
$$
BEGIN
 	IF NEW.FURNITURE_NAME <> OLD.FURNITURE_NAME THEN
		INSERT INTO Changes_Furniture(UPDATED_AT, OLD_FURNITURE_NAME, NEW_FURNITURE_NAME)
		VALUES(NOW(), OLD.FURNITURE_NAME, NEW.FURNITURE_NAME);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER Show_Update_Furniture_Name 
BEFORE UPDATE ON Furniture
FOR EACH ROW EXECUTE FUNCTION Update_Furniture_Details();

UPDATE Furniture
SET FURNITURE_NAME = 'Door' WHERE FURNITURE_NAME = 'Table';

UPDATE Furniture
SET FURNITURE_NAME = 'Chair' WHERE FURNITURE_NAME = 'Armchair';

SELECT * FROM Changes_Furniture; 
