SELECT Category.FURNITURE_CATEGORY_NAME,Furniture_Price.FURNITURE_PRICE
FROM Furniture
JOIN Category ON Furniture.FURNITURE_CATEGORY_ID = Category.FURNITURE_CATEGORY_ID 
JOIN Furniture_Price ON Furniture.FURNITURE_ID = Furniture_Pricefood_id  

SELECT Furniture.FURNITURE_NAME, 
SUM(FURNITURE_PRICE) AS COST 
FROM Furniture
JOIN Furniture_Price ON Furniture.FURNITURE_ID = Furniture_Price.FURNITURE_ID
GROUP BY Furniture.FURNITURE_NAME

SELECT DISTINCT(Category.FURNITURE_CATEGORY_NAME),
COUNT(Furniture.FURNITURE_NAME) 
FROM Furniture  
JOIN Category ON Furniture.FURNITURE_CATEGORY_ID = Category.FURNITURE_CATEGORY_ID   
GROUP BY Category.FURNITURE_CATEGORY_NAME





