DO $$
 DECLARE
     FURNITURE_CATEGORY_ID   Category.FURNITURE_CATEGORY_ID%TYPE;
     FURNITURE_CATEGORY_NAME Category.FURNITURE_CATEGORY_NAME%TYPE;
 BEGIN
     FURNITURE_CATEGORY_ID := 10;
     FURNITURE_CATEGORY_NAME := 'Bed';
     FOR COUNTER IN 1..10
         LOOP
             INSERT INTO Category(FURNITURE_CATEGORY_ID, FURNITURE_CATEGORY_NAME)
            VALUES (COUNTER + FURNITURE_CATEGORY_ID, FURNITURE_CATEGORY_NAME || COUNTER);
         END LOOP;
 END;
 $$
